#!/usr/bin/env python3
"""
ORCA 6.0 Wrapper - Molecular DFT and Wavefunction Methods
Optimal for organometallics, coordination complexes, and molecular catalysts
"""
from pathlib import Path
from typing import Dict, Any, List, Optional
import os
import subprocess

from .base_wrapper import SimulationWrapper


class ORCAWrapper(SimulationWrapper):
    """
    Wrapper for ORCA 6.0 quantum chemistry package
    
    Capabilities:
    - Molecular DFT (B3LYP, PBE0, M06, etc.)
    - Broken-symmetry DFT for open-shell systems
    - Multireference (CASSCF, NEVPT2)
    - Relativistic methods (ZORA, DKH)
    
    Use cases:
    - Mo(N₂)(dppe)₂ complexes
    - Fe-porphyrin catalysts
    - Ruthenium N₂ complexes
    - All molecular organometallics
    """
    
    def __init__(self, app_path: Optional[str] = None, scratch_dir: Optional[str] = None):
        # Default ORCA installation path
        if not app_path:
            app_path = os.path.expanduser("~/APPS/orca")
            if not os.path.exists(app_path):
                app_path = "/Users/stevens/Dropbox/Backplane/APPS/orca"
        super().__init__(app_path, scratch_dir)
    
    def _detect_app_path(self) -> Path:
        """Detect ORCA installation"""
        common_paths = [
            Path.home() / "APPS" / "orca",
            Path("/Users/stevens/Dropbox/Backplane/APPS/orca"),
            Path("/opt/orca"),
            Path("/usr/local/orca"),
        ]
        
        for path in common_paths:
            if (path / "orca").exists():
                return path
        
        raise FileNotFoundError("ORCA installation not found. See INSTALLATION.md")
    
    def _validate_installation(self) -> bool:
        """Validate ORCA installation"""
        orca_bin = self.app_path / "orca"
        if not orca_bin.exists():
            raise FileNotFoundError(f"ORCA binary not found at {orca_bin}")
        
        # Check if executable
        if not os.access(orca_bin, os.X_OK):
            raise PermissionError(f"ORCA binary at {orca_bin} is not executable")
        
        return True
    
    def _generate_input_file(self, job_params: Dict[str, Any], input_file: Path) -> None:
        """
        Generate ORCA input file
        
        TODO: Full implementation - see quantum_espresso.py for pattern
        
        Job params should include:
        - calculation_type: 'energy', 'optimization', 'frequency'
        - method: 'B3LYP', 'PBE0', 'M06', etc.
        - basis_set: 'def2-SVP', 'def2-TZVP', etc.
        - charge: 0
        - multiplicity: 1
        - structure: atomic coordinates (from SMILES or XYZ)
        """
        # Placeholder implementation
        method = job_params.get('method', 'B3LYP')
        basis = job_params.get('basis_set', 'def2-SVP')
        calc_type = job_params.get('calculation_type', 'energy')
        
        # Simple input template
        input_content = f"# ORCA Input - Generated by Backplane\n"
        input_content += f"! {method} {basis}\n"
        if calc_type == 'optimization':
            input_content += "! Opt\n"
        elif calc_type == 'frequency':
            input_content += "! Freq\n"
        input_content += "\n* xyz 0 1\n"
        input_content += "# TODO: Add atomic coordinates from job_params\n"
        input_content += "*\n"
        
        input_file.write_text(input_content)
    
    def _parse_output_file(self, output_file: Path, job_dir: Path) -> Dict[str, Any]:
        """
        Parse ORCA output file
        
        TODO: Full implementation - extract:
        - Final energy
        - Optimized geometry
        - Frequencies
        - Spin densities
        - Mulliken charges
        """
        results = {
            'status': 'completed',
            'energy': None,
            'message': 'ORCA wrapper - TODO: implement output parsing'
        }
        
        if output_file.exists():
            content = output_file.read_text()
            # Look for final energy
            for line in content.split('\n'):
                if 'FINAL SINGLE POINT ENERGY' in line:
                    try:
                        energy = float(line.split()[-1])
                        results['energy'] = energy
                    except:
                        pass
        
        return results
    
    def _get_run_command(self, input_file: Path, output_file: Path, job_dir: Path) -> List[str]:
        """Get ORCA execution command"""
        orca_bin = str(self.app_path / "orca")
        return [orca_bin, str(input_file)]


def create_orca_wrapper(app_path: Optional[str] = None) -> ORCAWrapper:
    """Factory function to create ORCA wrapper"""
    return ORCAWrapper(app_path=app_path)
